railsware/js-routes

lib/js_routes.rb
Some gems and initializers attempt to generate javascript, which can include the routes file, prior to routes be initialized. This addition provides insurance against that.
Notably: This gem will not work with the [react-rails gem](https://github.com/reactjs/react-rails), due to what happens in the call on this line: https://github.com/reactjs/react-rails/blob/1c03b00b8105c78fbf674abe34be4941084bede4/lib/react/rails/railtie.rb#L62
Manifests, which may include js-routes will be rendered prior to routes being loaded, resulting in an empty set of routes being generated.
This is not, however, the only case where this bug can occur. It happens any time routes are accessed inside an initializer, or in a rails app's `after_initialize` hook.
=> Ensure routes are loaded, prior to generating them

CHANGELOG.md, lib/js_routes/engine.rb
This fixes a bug that that crashed the Gem when you have a space in your path.
=> URL escape routes.rb url to fix bad `URI(is not URI?)` error

lib/js_routes.rb, lib/routes.js, lib/routes.js.coffee, spec/js_routes/generated_javascript_spec.rb, spec/js_routes/options_spec.rb, spec/js_routes/rails_routes_compatibility_spec.rb
Here's a first pass on a configurable serializer for issue #153.
Usage is as described in that issue.
```ruby
JsRoutes.setup do |config|
config.serializer = "myApp.myCustomSerializerFn"
end
```
Also note that I removed a bunch of "if jQuery present" specs as they should no longer be relevant.
If everything looks good to you guys, I'll update the readme.
Let me know if you guys have any questions.
Thanks!
=> Allow Configurable Serializer Function (Solves #153)

Readme.md, lib/js_routes.rb, spec/js_routes/options_spec.rb
* Adds support for using the window.location.protocol when a protocol has not been specified.
* Adds support for using the window.location.host when a host has not been specified.
* Adds support for using the window.location.port when a port has not been specified.
Fixes #157.
@bogdan and @le0pard please review.
=> Add window.location fallback for missing host parts

lib/js_routes.rb
Fixes #171
This solution is compatible with all rails versions presented in Appraisal.
If you need to use it with sprockets v3, you can use:
> gem 'js-routes', github: 'vonagam/js-routes', branch: 'rails5'
=> fix named routes for rails 5

app/assets/javascripts/js-routes.js.erb, spec/js_routes/generated_javascript_spec.rb, spec/js_routes/zzz_last_post_rails_init_spec.rb
With sprockets 3, `file://` passed to [depend_on](https://github.com/rails/sprockets#the-depend_on-directive) causes `Sprockets::FileNotFound` error.
```
Sprockets::FileNotFound - couldn't find file 'file:///Users/ihara/Documents/work/kintan/config/routes.rb':
sprockets (3.5.2) lib/sprockets/resolve.rb:64:in `resolve!'
sprockets (3.5.2) lib/sprockets/context.rb:88:in `resolve'
sprockets (3.5.2) lib/sprockets/legacy.rb:259:in `resolve_with_compat'
sprockets (3.5.2) lib/sprockets/context.rb:116:in `depend_on'
js-routes (1.2.2) app/assets/javascripts/js-routes.js.erb:2:in `_evaluate_template'
...
```
gem's versions are here
* rails (4.2.5)
* js-routes (1.2.2)
* sprockets (3.5.2)
* sprockets-rails (3.0.0)
Do you need to add `file://`?
=> Remove file url scheme for sprockets 3

lib/js_routes.rb, spec/js_routes/rails_routes_compatibility_spec.rb, spec/spec_helper.rb
Having routes with `constraints: {subdomain: 'backend'}`, it generates paths, such as `/?subdomain=backend`.
=> Filter "subdomain" default parameter

lib/js_routes.rb
This fixes #181.
Sorting `Rails.application.routes.named_routes.to_a` by `to_s` was introduced in d7dcfd45ae59dd8bea595f3bc5598567a0ec82f5, which was supposed to sort every route by key.
Rails.application.routes.named_routes.to_a.first.to_s returns a string like this:
```
"[:root, #<ActionDispatch::Journey::Route:0x0000a8ecc362f8 @name="root", @app=#<ActionDispatch::Routing::RouteSet::Dispatcher:0x0000a8ecc370b8 @defaults={:controller=>"application", :action=>"index"}>, @path=#<ActionDispatch::Journey::Path::Pattern:0x0000a8ecc36f78 @spec=#<ActionDispatch::Journey::Nodes::Slash:0x0000a8ecc486d8 @left="/", @memo=nil>, @requirements={}, @separators="/.?", @anchored=true, @names=[], @optional_names=[], @required_names=[], @re=nil, @offsets=nil>, …
```
=> Sort by the route key instead of the entire AST.

Readme.md, lib/js_routes.rb
Issue #186:
Take the default for the `prefix` configuration setting from the Rails relative URL root setting (`Rails.application.config.relative_url_root`).
Add a note in the README about how to set the relative URL root correctly during asset precompilation.
=> Default prefix setting to Rails relative URL root setting

spec/js_routes/options_spec.rb, spec/spec_helper.rb
```ruby
Failure/Error: expect(evaljs("Routes.foo_all_path()")).to eq(routes.foo_all_path(:format => "json"))
expected: "/other_optional.json"
got: "/other_optional/.json"
```
=> Failing spec

.travis.yml, CHANGELOG.md, js-routes.gemspec, lib/routes.js, lib/routes.js.coffee, spec/js_routes/options_spec.rb, spec/spec_helper.rb
Reasons:
* New v8 engine (5.x instead 3.x in therubyracer gem)
* Simple interface, which provide better way to debug JS output (result - `log` function much simpler)
Reason to remove "no `indexOf`" test:
* no engines, which is not have this basic function - https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf look at "Browser compatibility" section
* we already using `indexOf` in another places and not checking availability. Example: https://github.com/railsware/js-routes/blob/master/lib/routes.js.coffee#L112
=> Drop 1.9.3 support and add indexOf helper

lib/js_routes/engine.rb
Sprockets 3.x display deprecation warning: You are using the a deprecated processor interface #<Proc:0x007f9002044f90@/.../gems/ruby-2.3.1/gems/js-routes-1.2.7/lib/js_routes/engine.rb:11>.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
I've followed the guide and updated the engine to support all versions of sprockets.
This makes two tests fail, but it looks like it's because those tests are implementation specific. I've checked this code on three fresh applications with sprockets 2.12.4, 3.7.0 and 4.0.0beta2. JavaScript `Routes` object is correctly created in all three cases.
=> Update Sprockets extension to work with Sprockets 2, 3, 4

lib/js_routes/engine.rb
Changed the code to be like 
https://github.com/fnando/i18n-js/pull/418
This changed is tested by me with 
- sprockets 3.7
- rails 4.1.x
using method specified in #211 
`Rails.application.assets.preprocessors` does include `JsRoutesSprocketsExtension`
after this change
=> Try to fix sprockets hook when using different sprockets/rails versions

lib/js_routes.rb, spec/js_routes/options_spec.rb
Hey, first off, thanks for the awesome work on this gem! 👍 
This adds the ability to generate routes from a Rails engine.
```erb
<%= JsRoutes.generate(engine: Blazer::Engine) %>
```
I've attempted to use this for [Blazer](https://github.com/ankane/blazer), but am running into issues with different route names depending on where users mount the engine. If mounted at `/`, it generates `Routes.blazer_queries_path()`, but if namespaced under `admin`, it generates `Routes.admin_blazer_queries_path()`, which makes sense for the typical setup.
Let me know your thoughts. Thanks!
=> Added `application` option

Readme.md, lib/routes.js, lib/routes.js.coffee
Sometimes it is useful to have dynamically determined base url with statically declared subdomains (as ex. for 'api.' subdomain in RESTful applications), so I've added the 'subdomain' as possible default_url_option.
=> Subdomain added as possible default_url_option

lib/routes.js, lib/routes.js.coffee, spec/js_routes/rails_routes_compatibility_spec.rb
With the current implementation of the ParameterMissing custom error type, function names can become obfuscated or dropped in the resulting stack trace. This PR updates the implementation based on the recommendations [from the mozilla developer docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#ES5_Custom_Error_Object).
I was able to reproduce the problem in our application with the help of [error-stack-parser](https://github.com/stacktracejs/error-stack-parser) to print the function names from the stacktrace.
```javascript
import Routes from 'routes';
import ErrorStackParser from 'error-stack-parser';
function doSomething() {
// should take an argument
Routes.account_path();
}
class SomeView {
handleClick() {
try {
doSomething();
} catch (error) …
```
=> Change ParameterMissing custom error implementation

lib/js_routes.rb, spec/js_routes/zzz_last_post_rails_init_spec.rb
Generating `routes.js` file using rake task rewrites it completely each time. So, asset pipeline or webpacker would recompile assets in case when content wasn't changed (because mtime of `routes.js` was changed).
This PR just skip write to output file, if file already exist and have same content. This way mtime became unchanged and asset pipeline or webpacker properly skip assets recompile.
Mostly same as https://github.com/fnando/i18n-js/pull/473 that solved same problem for `i18n-js` gem.
=> Avoid rewrite js file if content wasn't changed.

lib/routes.js, lib/routes.js.coffee, spec/js_routes/rails_routes_compatibility_spec.rb
Resolves https://github.com/railsware/js-routes/issues/243
@le0pard Thanks for replying to the issue 👍 I played a bit around with this and got the specs passing.
If you ask me, the changes I'm proposing here are breaking changes, requiring bumping the major version. This change will actually break my usage of `js-routes` because I'm doing the URI-encoding myself and then passing it into the generated route functions. That way I would end up with URI-encoding twice.
Alternatively this change could be configured with a new config option (which is disabled by default).
Happy to hear what y'all think :v:
=> URI-encode route parts

lib/js_routes.rb
**What** Fix a `LocalJumpError` I get when on the second launch of my app
**What's the bug**
Using return inside a block can lead to a `LocalJumpError` if the
block is invoked later instead of immediately. This [stack overflow has a few more details](https://stackoverflow.com/questions/2325471/using-return-in-a-ruby-block)
<details><summary>Simple Proof of Concept</summary><p>
```
$callbacks = []
$initialized = false
def after_initialize(&block)
if $initialized
p [:yield]
block.call
else
$callbacks << block
end
end
def finalize
$callbacks.each(&:call)
$initialized = true
end
def set_callback
after_initialize do
return
end
end
```
```
set_callback
finalize
```
```
finalize
set_callback
```
</p></details>
The tests for this change passed because the rails app is already initialized (in the …
=> Use next, not return in after_initialize block

lib/routes.js, lib/routes.ts, spec/js_routes/options_spec.rb, spec/support/routes.rb
Uses `default_url_options` configuration option as the basis to then overwrite with the options hash passed in the context of partitioning the parameters.
Please let me know if you see any improvements I can make!
Thanks again for all your effort!
=> Use default_url_options as base options hash (#289)

lib/js_routes/generators/middleware.rb
Current code crashes as JsRoutes is a module.
=> use configuration class directly

Readme.md
This PR is to add a status badge to display the results of a GitHub action.
How about this PR?
I have confirmed that the Github Action result badge appears in my repository.
https://github.com/madogiwa0124/js-routes/blob/c6429e12388707895cda444e36745824dc1bcffc/Readme.md
=> Add GitHub actions for status badge to README.

Readme.md, lib/js_routes/route.rb, spec/js_routes/module_types/dts_spec.rb, spec/js_routes/module_types/esm_spec.rb
Closes #307.
I added the `#__PURE__` comment to `Route#body` like you suggested and that worked great! Just needed to make a few small test changes. 
It would be nice to add a test to ensure Webpack does tree-shake the output, I'm just not sure how I'd do that. But given the results of my example repo, I think we can be pretty confident that this change will work.
Thanks in advance for the review and feel free to make any changes!
=> Add #__PURE__ to __jsr.r call in ESM output only, update tests.

lib/js_routes/generators/base.rb, spec/js_routes/module_types/umd_spec.rb, spec/js_routes/zzz_last_post_rails_init_spec.rb
The deprecated `File.exists?` alias was removed on Ruby 3.2.0.
`File.exist?` works on all versions.
ref: https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
=> fix: rename `File.exists?` to `File.exist?`

lib/js_routes.rb, spec/js_routes/module_types/dts_spec.rb
Hi!
I have a simple project that doesn't use any import/export modules and is still using sprockets. 
On latest version, if I have this configuration:
```ruby
JsRoutes.setup do |c|
c.module_type = nil
c.namespace = 'Routes'
end
```
It breaks like this when I load any endpoint:
After reviewing, I noticed that 'DTS' was being used by default causing this clash. I solved it by monkey patching it on my project, but I thought I would suggest this modification to support the intended behavior of prioritizing DTS only if the configuration_type has not been set.
=> Fix broken configuration when module_type is Nil and namespace is being used.

lib/tasks/js_routes.rake
`js:routes:typescript` raise below error.
```
rake aborted!
NoMethodError: private method `warn' called for class ActiveSupport::Deprecation (NoMethodError)
ActiveSupport::Deprecation.warn(
^^^^^
/vendor/bundle/ruby/3.3.0/gems/js-routes-2.3.3/lib/tasks/js_routes.rake:11:in `block (3 levels) in <main>'
Tasks: TOP => js:routes:typescript
(See full trace by running task with --trace)
```
Because ActiveSupport::Deprecation.warn was removed from Rails 7.2.
=> Fix NoMethodError when run js:routes:typescript
